// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAubCNSG6TLk9qFW3YFpqE3c24ltd4eGKE',
    appId: '1:299973064267:web:1f311e9d50783206487fce',
    messagingSenderId: '299973064267',
    projectId: 'ecommerce-85',
    authDomain: 'ecommerce-85.firebaseapp.com',
    storageBucket: 'ecommerce-85.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDdajRxsBktBzlI8FhbImTC9G-od4v_hc',
    appId: '1:299973064267:android:da33497933378eac487fce',
    messagingSenderId: '299973064267',
    projectId: 'ecommerce-85',
    storageBucket: 'ecommerce-85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDf1I6l5YgUIenKV2cvKU-QdYMKN14xGU',
    appId: '1:299973064267:ios:654d6f2e13fac833487fce',
    messagingSenderId: '299973064267',
    projectId: 'ecommerce-85',
    storageBucket: 'ecommerce-85.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDf1I6l5YgUIenKV2cvKU-QdYMKN14xGU',
    appId: '1:299973064267:ios:654d6f2e13fac833487fce',
    messagingSenderId: '299973064267',
    projectId: 'ecommerce-85',
    storageBucket: 'ecommerce-85.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAubCNSG6TLk9qFW3YFpqE3c24ltd4eGKE',
    appId: '1:299973064267:web:51bb83f8f58e02ba487fce',
    messagingSenderId: '299973064267',
    projectId: 'ecommerce-85',
    authDomain: 'ecommerce-85.firebaseapp.com',
    storageBucket: 'ecommerce-85.firebasestorage.app',
  );
}
